---
kind: pipeline
type: docker
name: stage

clone:
  disable: true

steps:
- name: git-test
  image: appleboy/drone-ssh
  settings:
    host:
    - from_secret: PRIVATE_IP_STAGE
    username: dev
    key:
      from_secret: DEPLOY_KEY
    port: 22
    command_timeout: 2m
    script:
    - mkdir hello

trigger:
  branch:
  - main
