---
kind: pipeline
type: ssh
name: stage

server:
  host: 10.0.1.142
  user: dev
  ssh_key:
    from_secret: DEPLOY_KEY

clone:
  disable: true

steps:
  - name: pull
    commands:
      - cd /var/www
      - mkdir hello
