---
kind: pipeline
type: docker
name: stage

clone:
  disable: true

steps:
- name: git-test
  image: appleboy/drone-ssh
  settings:
    host:
      from_secret: PRIVATE_IP_STAGE
    username: dev
    key:
      from_secret: DEPLOY_KEY
    port: 22
    command_timeout: 2m
    script:
    - pkill -15 -e -c -f "/var/www/assistant/venv/bin/python3 manage.py pdf_process"

trigger:
  branch:
  - main
  event:
  - custom
