---
kind: pipeline
type: docker
name: stage

clone:
  disable: true

steps:
- name: git-pull
  image: appleboy/drone-ssh
  settings:
    host:
    - 10.0.1.142
    username: dev
    key:
      from_secret: DEPLOY_KEY
    port: 22
    command_timeout: 2m
    script:
    - mkdir hello2
    - cd hello
    - mkdir world

trigger:
  branch:
  - main
