---
kind: pipeline
type: ssh
name: default

server:
  host: 10.0.1.142
  user: dev
  ssh_key:
    from_secret: stage_rsa_key
  
clone:
  disable: true

steps:
- name: test
  commands:
  - cd /var/www
  - mkdir hello
  - cd hello
  - touch world.txt

trigger:
  branch:
  - main
  event:
  - push
